### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [TomasZmek/porn-videos-embed#1]
What do I need and how do I install it?

**Comment by TomasZmek** [comment]
You need newest version Wordpress. 
Download zip https://github.com/TomasZmek/porn-videos-embed/releases
Unzip all and folder upload to your webserver /wp-content/plugins
Rename folder to porn-videos-embed 

Or you can install from official wordpress plugins repository. The name plugins is Porn Videos Embed. 
https://wordpress.org/plugins/porn-videos-embed/
